### ISSUE TITLE
TextField returned as NClob

### ISSUE THREAD

**Issue by amarvin** [mathebox/django_hana_pyhdb#16]
#### What is the expected behavior?
Queries of a TextField using Django-hana-pyhdb should return a string, not a NClob object.

#### What is the current behavior?
For TextFields, pyhdb returns a Python object of class pyhdb.protocol.lobs.NClob. This causes issues when other packages expect a string object and instead receive an NClob object. I see that in base.py, you map Django TextField field type to HANA's NCLOB field type. Is there a way to pass the response of a query through str() to convert it from NClob to string?

#### What are the steps to reproduce?
Create a HANA database table with a TextField type field, then query an entry from that field and see that the returned Python object is an NClob.

#### Which versions of Python and Django are affected?
Python 3.5 and Django 1.10.3.

#### Is there anything else we should know?
Nope.

**Comment by amarvin** [comment]
I discovered this issue when using Django-Jet, which creates a TextField named SETTINGS in the table DASHBOARD_USERDASHBOARDMODULE. One value stored in that field is
`{"limit": 10, "user": null, "include_list": null, "exclude_list": null}`
later I get an error saying that this NClob object cannot be indexed. This occurs when it tried to convert the NClob to a Python object using json.loads():
`self.settings = json.loads(self.model.settings)`
where self.model.settings was a queryset that returns the NClob from HANA.

I can manually fix the error, if I instead change it to:
`self.settings = json.loads(str(self.model.settings))`

**Comment by amarvin** [comment]
This problem was faced in the Django development of the Oracle backend as well. We could learn from the approach there. In the operations.py file for example, there some functions for converting TextField responses from LOB to string: https://github.com/django/django/blob/master/django/db/backends/oracle/operations.py
specifically DatabaseOperations.get_db_converters()

**Comment by amarvin** [comment]
Here's an idea for a unit test: create a model with a TextField with some data, query a value from the TextField, and check that it is a string (and not a Pyhdb object, like NClob, Clob or LOB).

**Comment by mathebox** [comment]
~~Good point. The tricky part is that `DatabaseOperations.get_db_converters` is available since django 1.10. But we have to support older versions as well.~~

**Edit**
Sorry, that was a false answer. `DatabaseOperations.get_db_converters` is also available in Django 1.8.

**Comment by mathebox** [comment]
Fixed by #24
