### ISSUE TITLE
Feature request: a versioned copy of the code

### ISSUE THREAD

**Issue by carlsoane** [mathebox/django_hana_pyhdb#26]
#### What is the expected behavior?
I am writing a tutorial for the next release of HANA Express(HXE) that shows someone how to execute the Django tutorial against HXE. With fix #23, I can now run the tutorial smoothly. I would like to be able to reference a tag or version number of the django_hana_pyhdb code that had been tested with HXE to avoid the user encountering regressions should they download a later revision of the code. 

Ideally, I would be able to install django_hana_pyhdb using pip.

#### What is the current behavior?
I have to pull the head or by commit #.

#### What are the steps to reproduce?
N/A

#### Which versions of Python and Django are affected?
All.

#### Is there anything else we should know?

**Comment by mathebox** [comment]
Hi @carlsoane!

It's great hearing that this repo will be promoted in a Django tutorial. But please keep in mind that the code is still lacking in tests and **there will be errors!** I'm only working on this in my spare time.

I will not create a tagged version before reaching a (very) good code coverage.
But you can already specify a commit for your pip requirements: http://stackoverflow.com/a/13754517/7414898
