### ISSUE TITLE
Quotes in SQL

### ISSUE THREAD

**Issue by amarvin** [mathebox/django_hana_pyhdb#9]
Django_hana_pyhdb creates SQL statements like:
`statement = 'select (1) as a from schemas where schema_name="MY_SCHEMA"'`
which for some reason causes an error for my version of SAP HANA. Surprisingly, this statement works though:
`statement = "select (1) as a from schemas where schema_name='MY_SCHEMA'"`

Is there an easy to wait switch between these two quotation formats? They should be identical within Python.

**Comment by amarvin** [comment]
This only seems to be necessary for me in django_hana_pyhdb at two places:
introspection.py, where line 30 and 31 swap single and double quotes (both ways), so that line 30 becomes:
`"select table_name, 't' from tables where schema_name='{0}' "`

and in base.py line 317, which becomes:
`cursor.execute("select (1) as a from schemas where schema_name='%s'" % self.default_schema)`

**Comment by amarvin** [comment]
Looking at one of the recent commits (https://github.com/mathebox/django_hana_pyhdb/commit/157ab40c079e9075ef75de49808bf8129d51f4aa), it looks like maybe an automatic PEP8 formatting was done that swapped some double quotes, which were needed by SQL, with single quotes. Should be straightforward to rollback those changes.

**Comment by mathebox** [comment]
You're completely right. Sorry. Should be fixed.

**Comment by amarvin** [comment]
Nice fix!
